// <auto-generated />
using System;
using DTHApplication.Shared.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTHApplication.Server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230301084916_addImageModel")]
    partial class addImageModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTHApplication.Shared.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79675121-4854-4266-9438-8b6e19a99c9b"),
                            CategoryName = "Mobile Phones",
                            Url = "mobile-phones"
                        },
                        new
                        {
                            Id = new Guid("bb3ebf6f-df7c-4298-8bc4-673093e41fb1"),
                            CategoryName = "Laptops",
                            Url = "laptops"
                        },
                        new
                        {
                            Id = new Guid("5ce4386e-ea5f-4548-a3a0-cb7ce81fa809"),
                            CategoryName = "Books",
                            Url = "books"
                        });
                });

            modelBuilder.Entity("DTHApplication.Shared.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcdc5ec2-e328-4bfd-9bbf-e9f1b67f0e91"),
                            IsMainImage = true,
                            ProductId = new Guid("879afcae-994a-4d68-a9da-2e8cb49c5c9f"),
                            URL = "https://didongviet.vn/pub/media/catalog/product//s/a/samsung-galaxy-s23-ultra-5g-mau-xanh.png"
                        },
                        new
                        {
                            Id = new Guid("ea9cfd4a-2537-46cf-b9d6-84c77672d741"),
                            IsMainImage = true,
                            ProductId = new Guid("d7873eda-0f41-4dda-9514-6df017559dbe"),
                            URL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhQl7FNuj_p9dROneitk5A3z9gafp65SD2Iw&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("920430e3-1298-4de3-890b-b383b233d5da"),
                            IsMainImage = true,
                            ProductId = new Guid("2d343e0f-53ed-440f-b1ac-6bbfd310fb4e"),
                            URL = "https://laptop88.vn/media/product/6927_dsc08733__6_.jpg"
                        });
                });

            modelBuilder.Entity("DTHApplication.Shared.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("879afcae-994a-4d68-a9da-2e8cb49c5c9f"),
                            CategoryId = new Guid("79675121-4854-4266-9438-8b6e19a99c9b"),
                            Description = "Samsung Galaxy S23 Ultra là điện thoại cao cấp của hãng điện thoại Samsung được ra mắt vào đầu năm 2023. Điện thoại Samsung S23 series mới này sở hữu camera độ phân giải 200MP ấn tượng cùng một khung viền vuông vức sang trọng. Cấu hình máy cũng là một điểm nổi bật với con chip Snapdragon 8 Gen 2 mạnh mẽ, bộ nhớ RAM 8GB mang lại hiệu suất xử lý vượt trội.",
                            Price = 31990000.0,
                            ProductName = "Samsung Galaxy S23 Ultra"
                        },
                        new
                        {
                            Id = new Guid("d7873eda-0f41-4dda-9514-6df017559dbe"),
                            CategoryId = new Guid("79675121-4854-4266-9438-8b6e19a99c9b"),
                            Description = "A magical new way to interact with iPhone. A vital new safety feature designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
                            Price = 28390000.0,
                            ProductName = "iPhone 14 Pro Max"
                        },
                        new
                        {
                            Id = new Guid("2d343e0f-53ed-440f-b1ac-6bbfd310fb4e"),
                            CategoryId = new Guid("bb3ebf6f-df7c-4298-8bc4-673093e41fb1"),
                            Description = "Chiếc laptop gaming Acer Nitro 5 i7 12700H là mẫu máy tính xách tay, laptop có cấu hình cao nhất nằm trong siêu phẩm Acer Nitro 5 mới ra mắt đến từ thương hiệu laptop Acer nổi tiếng. Mẫu laptop Acer Core i7 này đã được thay bằng một diện mạo hoàn toàn mới từ thiết kế cho tới cấu hình, sẽ cho các game thủ có được trải nghiệm chiến game cực đã; đồng thời máy còn đáp ứng tốt các công việc thiết kế đồ họa 3D phức tạp của người dùng khi là chiếc Acer Nitro duy nhất hiện nay được trang bị màn hình chuẩn màu. Để tìm hiểu chi tiết hơn về sản phẩm, các bạn hãy tham khảo ngay nội dung dưới đây nhé!",
                            Price = 26990000.0,
                            ProductName = "Laptop Acer Nitro 5 Tiger 2022 AN515-58-74B7"
                        });
                });

            modelBuilder.Entity("DTHApplication.Shared.Image", b =>
                {
                    b.HasOne("DTHApplication.Shared.Product", "Product")
                        .WithMany("ImageURLs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DTHApplication.Shared.Product", b =>
                {
                    b.HasOne("DTHApplication.Shared.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DTHApplication.Shared.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DTHApplication.Shared.Product", b =>
                {
                    b.Navigation("ImageURLs");
                });
#pragma warning restore 612, 618
        }
    }
}
